services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: addresses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres/addresses-postgres.sql:/docker-entrypoint-initdb.d/01-addresses.sql:ro

volumes:
  postgres_data:
